#!/bin/sh
xrdb $HOME/.Xresources

if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
        eval `dbus-launch --sh-syntax`
        echo "D-BUS per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
        echo $DBUS_SESSION_BUS_ADDRESS > /tmp/dbus-address
fi

exec fluxbox
sleep 3